<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ServerGarbageCollection>true</ServerGarbageCollection>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="FeynmanAppOutput_2026-07-18-14-32-48\**" />
	  <EmbeddedResource Remove="FeynmanAppOutput_2026-07-18-14-32-48\**" />
	  <None Remove="FeynmanAppOutput_2026-07-18-14-32-48\**" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Frameworks\CsvMaker\CsvMaker.csproj" />
	  <ProjectReference Include="..\BeagleLib\BeagleLib.csproj" />
	</ItemGroup>

</Project>
